name: CI to ECR

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names algoreview/fe --region ap-northeast-1 || \
          aws ecr create-repository --repository-name algoreview/fe --region ap-northeast-1

      - name: Set commit SHA as IMAGE_TAG
        id: vars
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - name: Build Docker image
        run: |
          docker build --cache-from=type=registry,ref=165304734991.dkr.ecr.ap-northeast-1.amazonaws.com/algoreview/fe:latest \
                       -t algoreview/fe:${{ env.IMAGE_TAG }} .

      - name: Tag Docker image
        run: |
          docker tag algoreview/fe:${{ env.IMAGE_TAG }} 165304734991.dkr.ecr.ap-northeast-1.amazonaws.com/algoreview/fe:${{ env.IMAGE_TAG }}
          docker tag algoreview/fe:${{ env.IMAGE_TAG }} 165304734991.dkr.ecr.ap-northeast-1.amazonaws.com/algoreview/fe:latest

      - name: Push to ECR
        run: |
          docker push 165304734991.dkr.ecr.ap-northeast-1.amazonaws.com/algoreview/fe:${{ env.IMAGE_TAG }}
          docker push 165304734991.dkr.ecr.ap-northeast-1.amazonaws.com/algoreview/fe:latest
